services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: mohirdev
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: employee_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mohirdev"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: employee-management
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_management
      SPRING_DATASOURCE_USERNAME: mohirdev
      SPRING_DATASOURCE_PASSWORD: 123
    volumes:
      - app_uploads:/app/uploads
  test:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_management
      SPRING_DATASOURCE_USERNAME: mohirdev
      SPRING_DATASOURCE_PASSWORD: 123
    command: ./gradlew test --no-daemon

volumes:
  postgres_data:
  app_uploads:
